name: Run Image Tests

on:
  workflow_dispatch:
      inputs:
        houdini-version:
          description: Houdini Version

env:
  CLIENT_ID: ${{ secrets.SESI_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.SESI_CLIENT_SECRET }}
  LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}

jobs:
  run-houdini-docker-image-tests:
    runs-on: ubuntu-latest

    container:
      image: captainhammy/hython-runner:${{ inputs.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Image Tests
        shell: bash
        run: |
          tests/run_built_container_tests.bash
