name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: 3.11

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
